apiVersion: v2
name: frx-crypto-scrape-demo-ms
description: Crypto forex value

home: https://github.com/lsmhun/frx-crypto-scrape-demo-ms

maintainers:
  - name: lsmhun

keywords:
  - kafka connect
  - data flow
  - grafana

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami/
  version: 10.3.16
- name: kafka
  repository: https://charts.bitnami.com/bitnami/
  version: 12.16.2
- name: kafka-connect-wrapper
  repository: https://lsmhun.github.io/lsmhun-helm-charts/
  version: 0.1.0
- condition: grafana.enabled
  name: grafana
  repository: https://charts.bitnami.com/bitnami/
  version: 5.2.9