# Default values for frx-crypto-scrape-demo-ms.

global:
  postgresql:
    postgresqlDatabase: "forex"
    postgresqlUsername: "admin"
    postgresqlPassword: "admin"
    servicePort: 5432

service:
  type: "NodePort"

ingress:
  enabled: false

grafana:
  enabled: true
  admin:
    password: "admin"
  dashboardsProvider:
    enabled: true
    configMapName:
  dashboardsConfigMaps: 
    - configMapName: dashboards-configmap
      fileName: "CRYPTO-2PANEL.json"
  datasources:
    secretName: grafana-datasource-secret

kafka-connect-wrapper:
  connectConfig:
    topics: "forex"
    logLevel: "INFO"
    worker:
      bootstrap: "frx-kafka:9092"
      keyConverter: "org.apache.kafka.connect.storage.StringConverter"
      valueConverter: "org.apache.kafka.connect.json.JsonConverter"
      valueConverterSchemasEnable: true
    source:
      enabled: false
    sink:
      enabled: true
      connectorClass: "io.confluent.connect.jdbc.JdbcSinkConnector"
      connectionUrl: "jdbc:postgresql://frx-postgresql:5432/forex"
      connectionUser: "admin"
      connectionPassword: "admin"
      keyConverter: "org.apache.kafka.connect.storage.StringConverter"
      valueConverter: "org.apache.kafka.connect.json.JsonConverter"
      valueConverterSchemasEnable: true

jobs:
  - name: btc-scrape
    image:
      repository: lsmaster/kafka-connect-wrapper
      tag: 6.1.0-0.1
      imagePullPolicy: IfNotPresent
    schedule: "* * * * *"
    command: ["/bin/bash"]
    args:
      - "-c"
      - "/opt/script/crypto-scrape.sh BTC USD,EUR"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 2
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    volumes:
      - name: script-mount
        configMap:
          name: script-configmap
          defaultMode: 0777
          items:
            - key: crypto-scrape.sh
              path: crypto-scrape.sh
    volumeMounts:
      - name: script-mount
        mountPath: /opt/script
  - name: eth-scrape
    image:
      repository: lsmaster/kafka-connect-wrapper
      tag: 6.1.0-0.1
      imagePullPolicy: IfNotPresent
    schedule: "* * * * *"
    command: ["/bin/bash"]
    args:
      - "-c"
      - "/opt/script/crypto-scrape.sh ETH USD,EUR"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 2
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    volumes:
      - name: script-mount
        configMap:
          name: script-configmap
          defaultMode: 0777
          items:
            - key: crypto-scrape.sh
              path: crypto-scrape.sh
    volumeMounts:
      - name: script-mount
        mountPath: /opt/script