apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-secret
type: Opaque
data:
  grafana-datasource.yaml: |-
{{ tpl (.Files.Get "dashboard/grafana-datasource.yaml") . | b64enc | indent 4 }}